steps:
  - name: 'gcr.io/$PROJECT_ID/orchid:latest'
    id: 'Compile'
    env:
      - 'BASE_URL=$_BASE_URL'
      - 'ENV=$_ENV'
      - 'SRC_DIR=$_SRC_DIR'
      - 'DEST_DIR=$_DEST_DIR'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build_Server'
    args: ['build',
           '--build-arg', 'STATIC_WEB_SERVER=http://${_STATIC_SERVER}/$SHORT_SHA',
           '--build-arg', 'NGINX_PORT=${_NGINX_PORT}',
           '--tag=gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:$SHORT_SHA',
           '.']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Static'
    args: ['-q', 'cp', '-r', '$_DEST_DIR', 'gs://${_STATIC_SERVER}/$SHORT_SHA']
    waitFor: ['Compile']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Update404'
    args: ['web', 'set', '-e', '${SHORT_SHA}/404.html', 'gs://${_STATIC_SERVER}']
    waitFor: ['Static']

  - name: "gcr.io/cloud-builders/docker"
    id: 'Push'
    args: ["push", "gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:$SHORT_SHA"]
    waitFor: ['Build_Server']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    args: ['beta', 'run', 'deploy', '${_ENV}/$REPO_NAME',
           '--platform=managed',
           '--region=europe-west1',
           '--allow-unauthenticated',
           '--image=gcr.io/$PROJECT_ID/$_ENV/$REPO_NAME:$SHORT_SHA']
    waitFor: ['Push', 'Static']
