# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: Leaking code
    siteDescription: Blog about of software development.
    avatar: 'assets/media/icon.png'

theme:
  social:
    github: 'guillerDev/leakingcode'

  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: 'taxonomy'
      taxonomyType: 'tags'
      includeTerms: true
      termsAtRoot: true

  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss' # this file is already available in the plugin's resources
  extraJs:
    - 'assets/js/extraJs.js'

taxonomies:
  collectionArchives:
    - collectionType: 'posts'
      collectionId: 'blog'
  taxonomies:
    - key: tags
      single: false
      orderBy:
        - entryCount

posts:
  postPages: # Common configuration for all posts
    layout: single # https://orchid.run/wiki/user-manual/core-concepts/templates#layouts
    components: # https://orchid.run/wiki/user-manual/core-concepts/components
      - type: pageContent
      - type: "disqus"
        shortname: "leakingcode"
